version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3888:3888"
    networks:
      - net
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - net
networks:
  net: